apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  namespace: maxweather
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: weather-service
          image: ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/maxweather-production/weather-service:latest
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
