apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-service
  namespace: maxweather
spec:
  rules:
    - host: api-staging.maxweather.internal
      http:
        paths:
          - path: /weather
            pathType: Prefix
            backend:
              service:
                name: weather-service
                port:
                  name: http
          - path: /forecast
            pathType: Prefix
            backend:
              service:
                name: weather-service
                port:
                  name: http
          - path: /health
            pathType: Exact
            backend:
              service:
                name: weather-service
                port:
                  name: http
